baseURL = 'https://coosis.github.io/blog/'
languageCode = 'en-us'
title = "Coosis's Blog"
theme="beautifulhug"

pygmentsUseClasses = true
pygmentsCodeFences = true

[Params]
    logo = "img/GreyHead2.png"
    favicon = "img/ClearHead2.ico"
    subtitle = "Coding related, mostly"
    useHLJS = true


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Coosis"
  email = "1159727122@qq.com"
  github = "Coosis"
  twitter = "Coosis2"
