baseURL = 'https://coosis.github.io/blog/'
languageCode = 'en-us'
title = "Coosis's Blog"
theme="m10c"
paginate = 8

#pygmentsUseClasses = true
#pygmentsCodeFences = true

#[Params]
#    logo = "img/GreyHead2.png"

#    useHLJS = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Coosis"
  avatar = "img/GreyHead2.png"
  description = "An ordinary coder."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/gohugoio"

  # Default theme
  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#57cc8a"