baseURL = 'https://coosis.github.io/'
languageCode = 'en-us'
# title = "Coosis's Blog"
# theme = 'beautifulhugo'

[Params.author]
  name = "Coosis"
  website = "https://coosis.github.io/"
  email = "coosislee@gmail.com"
  github = "Coosis"
  twitter = "CoosisV"
  # linkedin = "username"
  telegram = "Coosis"

[Params]
  homeTitle = "Coosis's Blog"
  subtitle = ""
  mainSections = ["post","posts"]
  logo = "img/ClearHead2.ico" # Expecting square dimensions
  favicon = "img/ClearHead2.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  # comments = true
  # readingTime = true
  # wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

